### ISSUE TITLE
Using with single hardwareserial arduinos

### ISSUE THREAD

**Issue by ImraanMitha** [gianmarcov/arduino_vesc#4]
In the VESC interface, the init function takes 2 HarwareSerial arguments but the Atmega 328p only has one hardware serial port, so is this library unusable with any boards based on the 328p?

**Comment by gianmarcov** [comment]
Hi, thank you for your feedback, i will remove it, what i want implement in the future, is that the library can be used outside of the Arduino world, so you pass an implemntation of the interface for reading and writing I/O and then the code will be called by the library.

Fast fix is to remove debugPort from the signature, later i will do the interface things.
https://github.com/gianmarcov/arduino_vesc/blob/9bdf8c0c197eeaf36641d0aeb6c112aa5b0f8d5a/vesc.cpp#L31

**Comment by gianmarcov** [comment]
I have removed the debugPort from the code. it's fixed.

The VESC has 3.3V UART some Arduinos has 5V Voltage I/O so you need a voltage devider or TTL logic level converter from 5V to 3.3V.
